---
- name: Upgrade all packages for Wantsome
  hosts: all
  become: yes
  gather_facts: yes
  strategy: free
  # serial: 100%
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - update-packages

- name: Install nginx for Wantsome
  hosts: webservers
  become: yes
  gather_facts: yes
  serial: 100%
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - nginx

- name: Install Wordpress for Wantsome
  hosts: wordpress
  become: yes
  gather_facts: yes
  serial: 100%
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - php
    - wordpress

- name: Install mysql for Wantsome
  hosts: database
  become: yes
  gather_facts: yes
  serial: 100%
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - mysql